files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.*'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 2
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
  function-name-format: 1
  id-name-format:
    - 1
    - convention: hyphenatedbem
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations: 0
  no-color-literals: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-qualifying-elements: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 1
    - order: concentric
  quotes:
    - 1
    - style: single
  single-line-per-selector: 0
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  variable-for-property:
    - 1
  variable-name-format: 1
